// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuTHw_rkObrrgI0iIexfPCthOJE-LUKjQ',
    appId: '1:1082106755553:web:4d40f870f6fc27d426baa0',
    messagingSenderId: '1082106755553',
    projectId: 'newzia-2ecf8',
    authDomain: 'newzia-2ecf8.firebaseapp.com',
    storageBucket: 'newzia-2ecf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9op8HoxBgf0z-4fGd9bL-9biZ2h5oVbU',
    appId: '1:1082106755553:android:6bcd40c337bbae8726baa0',
    messagingSenderId: '1082106755553',
    projectId: 'newzia-2ecf8',
    storageBucket: 'newzia-2ecf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNX3DBDZdufl_ZZIbexV65vuyGMJhsbs',
    appId: '1:1082106755553:ios:04cbdfd0f23e27c626baa0',
    messagingSenderId: '1082106755553',
    projectId: 'newzia-2ecf8',
    storageBucket: 'newzia-2ecf8.appspot.com',
    iosBundleId: 'com.example.newzia',
  );
}
